### ISSUE TITLE
compilation error with FLTK 1.3.8

### ISSUE THREAD

**Issue by ghost** [Rangi42/tilemap-studio#73]
can't compile on ArchLinux with gcc 12.2.0, FLTK 1.3.8 (natively installed via pacman from the official repos)

on tilemap studio 4.0.1, when compiling with `make` (on the unzipped directory, zipfile from github), I get several errors like this:

```
src/widgets.cpp:195:9: error: ‘Fl_Input Fl_Spinner::input_’ is private within this context                                                                                          
  195 |         input_.box(OS_INPUT_THIN_DOWN_BOX);
```

I attach full output from `make`
[4.0.1_make_output.txt](https://github.com/Rangi42/tilemap-studio/files/9651015/4.0.1_make_output.txt)

Similar errors happen on the latest commit (69b1d9a).

**Comment by Rangi42** [comment]
Yeah, follow the <https://github.com/Rangi42/tilemap-studio/blob/master/INSTALL.md#install-and-build-tilemap-studio> steps to build with the new ABI.

**Comment by ghost** [comment]
yeah, that did the trick, thanks 😀
